version: "3.9"
services:
  app:
    command: yarn start
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT}
        target: 3000
    links:
      - db
    depends_on:
      - "db"
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_KEY: ${OMDB_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  db:
      image: postgres
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
